// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package net.combatserver.protobuf;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageHandler
      implements com.google.protobuf.ProtocolMessageEnum {
    PolicyFileRequest(0, 15472),
    HttpGetRequest(1, 18245),
    HttpPostRequest(2, 20559),
    PingIntervalRequest(3, 300),
    RoomListNotice(4, 1),
    UserListNotice(5, 2),
    RegionListNotice(6, 3),
    NetSpeedRequest(7, 304),
    NetSpeedResponse(8, 5),
    GetRegionRequest(9, 6),
    GetRegionResponse(10, 7),
    CreateRoomRequest(11, 8),
    CreateRoomResponse(12, 9),
    NewRoomNotice(13, 10),
    RoomPropertyUpdateRequest(14, 11),
    RoomPropertyUpdateNotice(15, 12),
    UserPropertyUpdateRequest(16, 13),
    UserPropertyUpdateNotice(17, 14),
    PrivateMessageRequest(18, 25),
    MessageByNameRequest(19, 26),
    RoomMessageRequest(20, 27),
    RegionMessageRequest(21, 28),
    ServerMessageRequest(22, 29),
    NewMessageNotice(23, 30),
    PluginRequest(24, 40),
    PluginResponse(25, 41),
    PluginNotice(26, 42),
    JoinServerRequest(27, 50),
    JoinServerResponse(28, 51),
    JoinDefaultRoomRequest(29, 352),
    JoinRoomResponse(30, 53),
    ChangeRoomRequest(31, 54),
    ChangeRoomResponse(32, 55),
    NewUserNotice(33, 56),
    LogoutRequest(34, 60),
    UserLeaveNotice(35, 61),
    DisconnectedRequest(36, 62),
    RoomRemoveNotice(37, 68),
    ServerErrorResponse(38, 369),
    ServerTimeResponse(39, 380),
    ;
    
    public static final int PolicyFileRequest_VALUE = 15472;
    public static final int HttpGetRequest_VALUE = 18245;
    public static final int HttpPostRequest_VALUE = 20559;
    public static final int PingIntervalRequest_VALUE = 300;
    public static final int RoomListNotice_VALUE = 1;
    public static final int UserListNotice_VALUE = 2;
    public static final int RegionListNotice_VALUE = 3;
    public static final int NetSpeedRequest_VALUE = 304;
    public static final int NetSpeedResponse_VALUE = 5;
    public static final int GetRegionRequest_VALUE = 6;
    public static final int GetRegionResponse_VALUE = 7;
    public static final int CreateRoomRequest_VALUE = 8;
    public static final int CreateRoomResponse_VALUE = 9;
    public static final int NewRoomNotice_VALUE = 10;
    public static final int RoomPropertyUpdateRequest_VALUE = 11;
    public static final int RoomPropertyUpdateNotice_VALUE = 12;
    public static final int UserPropertyUpdateRequest_VALUE = 13;
    public static final int UserPropertyUpdateNotice_VALUE = 14;
    public static final int PrivateMessageRequest_VALUE = 25;
    public static final int MessageByNameRequest_VALUE = 26;
    public static final int RoomMessageRequest_VALUE = 27;
    public static final int RegionMessageRequest_VALUE = 28;
    public static final int ServerMessageRequest_VALUE = 29;
    public static final int NewMessageNotice_VALUE = 30;
    public static final int PluginRequest_VALUE = 40;
    public static final int PluginResponse_VALUE = 41;
    public static final int PluginNotice_VALUE = 42;
    public static final int JoinServerRequest_VALUE = 50;
    public static final int JoinServerResponse_VALUE = 51;
    public static final int JoinDefaultRoomRequest_VALUE = 352;
    public static final int JoinRoomResponse_VALUE = 53;
    public static final int ChangeRoomRequest_VALUE = 54;
    public static final int ChangeRoomResponse_VALUE = 55;
    public static final int NewUserNotice_VALUE = 56;
    public static final int LogoutRequest_VALUE = 60;
    public static final int UserLeaveNotice_VALUE = 61;
    public static final int DisconnectedRequest_VALUE = 62;
    public static final int RoomRemoveNotice_VALUE = 68;
    public static final int ServerErrorResponse_VALUE = 369;
    public static final int ServerTimeResponse_VALUE = 380;
    
    
    public final int getNumber() { return value; }
    
    public static MessageHandler valueOf(int value) {
      switch (value) {
        case 15472: return PolicyFileRequest;
        case 18245: return HttpGetRequest;
        case 20559: return HttpPostRequest;
        case 300: return PingIntervalRequest;
        case 1: return RoomListNotice;
        case 2: return UserListNotice;
        case 3: return RegionListNotice;
        case 304: return NetSpeedRequest;
        case 5: return NetSpeedResponse;
        case 6: return GetRegionRequest;
        case 7: return GetRegionResponse;
        case 8: return CreateRoomRequest;
        case 9: return CreateRoomResponse;
        case 10: return NewRoomNotice;
        case 11: return RoomPropertyUpdateRequest;
        case 12: return RoomPropertyUpdateNotice;
        case 13: return UserPropertyUpdateRequest;
        case 14: return UserPropertyUpdateNotice;
        case 25: return PrivateMessageRequest;
        case 26: return MessageByNameRequest;
        case 27: return RoomMessageRequest;
        case 28: return RegionMessageRequest;
        case 29: return ServerMessageRequest;
        case 30: return NewMessageNotice;
        case 40: return PluginRequest;
        case 41: return PluginResponse;
        case 42: return PluginNotice;
        case 50: return JoinServerRequest;
        case 51: return JoinServerResponse;
        case 352: return JoinDefaultRoomRequest;
        case 53: return JoinRoomResponse;
        case 54: return ChangeRoomRequest;
        case 55: return ChangeRoomResponse;
        case 56: return NewUserNotice;
        case 60: return LogoutRequest;
        case 61: return UserLeaveNotice;
        case 62: return DisconnectedRequest;
        case 68: return RoomRemoveNotice;
        case 369: return ServerErrorResponse;
        case 380: return ServerTimeResponse;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageHandler>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageHandler>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageHandler>() {
            public MessageHandler findValueByNumber(int number) {
              return MessageHandler.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.combatserver.protobuf.Protocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageHandler[] VALUES = {
      PolicyFileRequest, HttpGetRequest, HttpPostRequest, PingIntervalRequest, RoomListNotice, UserListNotice, RegionListNotice, NetSpeedRequest, NetSpeedResponse, GetRegionRequest, GetRegionResponse, CreateRoomRequest, CreateRoomResponse, NewRoomNotice, RoomPropertyUpdateRequest, RoomPropertyUpdateNotice, UserPropertyUpdateRequest, UserPropertyUpdateNotice, PrivateMessageRequest, MessageByNameRequest, RoomMessageRequest, RegionMessageRequest, ServerMessageRequest, NewMessageNotice, PluginRequest, PluginResponse, PluginNotice, JoinServerRequest, JoinServerResponse, JoinDefaultRoomRequest, JoinRoomResponse, ChangeRoomRequest, ChangeRoomResponse, NewUserNotice, LogoutRequest, UserLeaveNotice, DisconnectedRequest, RoomRemoveNotice, ServerErrorResponse, ServerTimeResponse, 
    };
    
    public static MessageHandler valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageHandler(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:net.combatserver.protobuf.MessageHandler)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protocol.proto\022\031net.combatserver.proto" +
      "buf*\300\007\n\016MessageHandler\022\026\n\021PolicyFileRequ" +
      "est\020\360x\022\024\n\016HttpGetRequest\020\305\216\001\022\025\n\017HttpPost" +
      "Request\020\317\240\001\022\030\n\023PingIntervalRequest\020\254\002\022\022\n" +
      "\016RoomListNotice\020\001\022\022\n\016UserListNotice\020\002\022\024\n" +
      "\020RegionListNotice\020\003\022\024\n\017NetSpeedRequest\020\260" +
      "\002\022\024\n\020NetSpeedResponse\020\005\022\024\n\020GetRegionRequ" +
      "est\020\006\022\025\n\021GetRegionResponse\020\007\022\025\n\021CreateRo" +
      "omRequest\020\010\022\026\n\022CreateRoomResponse\020\t\022\021\n\rN" +
      "ewRoomNotice\020\n\022\035\n\031RoomPropertyUpdateRequ",
      "est\020\013\022\034\n\030RoomPropertyUpdateNotice\020\014\022\035\n\031U" +
      "serPropertyUpdateRequest\020\r\022\034\n\030UserProper" +
      "tyUpdateNotice\020\016\022\031\n\025PrivateMessageReques" +
      "t\020\031\022\030\n\024MessageByNameRequest\020\032\022\026\n\022RoomMes" +
      "sageRequest\020\033\022\030\n\024RegionMessageRequest\020\034\022" +
      "\030\n\024ServerMessageRequest\020\035\022\024\n\020NewMessageN" +
      "otice\020\036\022\021\n\rPluginRequest\020(\022\022\n\016PluginResp" +
      "onse\020)\022\020\n\014PluginNotice\020*\022\025\n\021JoinServerRe" +
      "quest\0202\022\026\n\022JoinServerResponse\0203\022\033\n\026JoinD" +
      "efaultRoomRequest\020\340\002\022\024\n\020JoinRoomResponse",
      "\0205\022\025\n\021ChangeRoomRequest\0206\022\026\n\022ChangeRoomR" +
      "esponse\0207\022\021\n\rNewUserNotice\0208\022\021\n\rLogoutRe" +
      "quest\020<\022\023\n\017UserLeaveNotice\020=\022\027\n\023Disconne" +
      "ctedRequest\020>\022\024\n\020RoomRemoveNotice\020D\022\030\n\023S" +
      "erverErrorResponse\020\361\002\022\027\n\022ServerTimeRespo" +
      "nse\020\374\002B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
