// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegionList.proto

package net.combatserver.protobuf;

public final class RegionList {
  private RegionList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegionListNoticeDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .net.combatserver.protobuf.Region region = 1;
    java.util.List<net.combatserver.protobuf.DataStructures.Region> 
        getRegionList();
    net.combatserver.protobuf.DataStructures.Region getRegion(int index);
    int getRegionCount();
    java.util.List<? extends net.combatserver.protobuf.DataStructures.RegionOrBuilder> 
        getRegionOrBuilderList();
    net.combatserver.protobuf.DataStructures.RegionOrBuilder getRegionOrBuilder(
        int index);
  }
  public static final class RegionListNoticeData extends
      com.google.protobuf.GeneratedMessage
      implements RegionListNoticeDataOrBuilder {
    // Use RegionListNoticeData.newBuilder() to construct.
    private RegionListNoticeData(Builder builder) {
      super(builder);
    }
    private RegionListNoticeData(boolean noInit) {}
    
    private static final RegionListNoticeData defaultInstance;
    public static RegionListNoticeData getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegionListNoticeData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.combatserver.protobuf.RegionList.internal_static_net_combatserver_protobuf_RegionListNoticeData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.combatserver.protobuf.RegionList.internal_static_net_combatserver_protobuf_RegionListNoticeData_fieldAccessorTable;
    }
    
    // repeated .net.combatserver.protobuf.Region region = 1;
    public static final int REGION_FIELD_NUMBER = 1;
    private java.util.List<net.combatserver.protobuf.DataStructures.Region> region_;
    public java.util.List<net.combatserver.protobuf.DataStructures.Region> getRegionList() {
      return region_;
    }
    public java.util.List<? extends net.combatserver.protobuf.DataStructures.RegionOrBuilder> 
        getRegionOrBuilderList() {
      return region_;
    }
    public int getRegionCount() {
      return region_.size();
    }
    public net.combatserver.protobuf.DataStructures.Region getRegion(int index) {
      return region_.get(index);
    }
    public net.combatserver.protobuf.DataStructures.RegionOrBuilder getRegionOrBuilder(
        int index) {
      return region_.get(index);
    }
    
    private void initFields() {
      region_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getRegionCount(); i++) {
        if (!getRegion(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < region_.size(); i++) {
        output.writeMessage(1, region_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < region_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, region_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.RegionList.RegionListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.combatserver.protobuf.RegionList.RegionListNoticeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.combatserver.protobuf.RegionList.RegionListNoticeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.combatserver.protobuf.RegionList.internal_static_net_combatserver_protobuf_RegionListNoticeData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.combatserver.protobuf.RegionList.internal_static_net_combatserver_protobuf_RegionListNoticeData_fieldAccessorTable;
      }
      
      // Construct using net.combatserver.protobuf.RegionList.RegionListNoticeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRegionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (regionBuilder_ == null) {
          region_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          regionBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.combatserver.protobuf.RegionList.RegionListNoticeData.getDescriptor();
      }
      
      public net.combatserver.protobuf.RegionList.RegionListNoticeData getDefaultInstanceForType() {
        return net.combatserver.protobuf.RegionList.RegionListNoticeData.getDefaultInstance();
      }
      
      public net.combatserver.protobuf.RegionList.RegionListNoticeData build() {
        net.combatserver.protobuf.RegionList.RegionListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.combatserver.protobuf.RegionList.RegionListNoticeData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.combatserver.protobuf.RegionList.RegionListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.combatserver.protobuf.RegionList.RegionListNoticeData buildPartial() {
        net.combatserver.protobuf.RegionList.RegionListNoticeData result = new net.combatserver.protobuf.RegionList.RegionListNoticeData(this);
        int from_bitField0_ = bitField0_;
        if (regionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            region_ = java.util.Collections.unmodifiableList(region_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.region_ = region_;
        } else {
          result.region_ = regionBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.combatserver.protobuf.RegionList.RegionListNoticeData) {
          return mergeFrom((net.combatserver.protobuf.RegionList.RegionListNoticeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.combatserver.protobuf.RegionList.RegionListNoticeData other) {
        if (other == net.combatserver.protobuf.RegionList.RegionListNoticeData.getDefaultInstance()) return this;
        if (regionBuilder_ == null) {
          if (!other.region_.isEmpty()) {
            if (region_.isEmpty()) {
              region_ = other.region_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRegionIsMutable();
              region_.addAll(other.region_);
            }
            onChanged();
          }
        } else {
          if (!other.region_.isEmpty()) {
            if (regionBuilder_.isEmpty()) {
              regionBuilder_.dispose();
              regionBuilder_ = null;
              region_ = other.region_;
              bitField0_ = (bitField0_ & ~0x00000001);
              regionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRegionFieldBuilder() : null;
            } else {
              regionBuilder_.addAllMessages(other.region_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getRegionCount(); i++) {
          if (!getRegion(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              net.combatserver.protobuf.DataStructures.Region.Builder subBuilder = net.combatserver.protobuf.DataStructures.Region.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRegion(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .net.combatserver.protobuf.Region region = 1;
      private java.util.List<net.combatserver.protobuf.DataStructures.Region> region_ =
        java.util.Collections.emptyList();
      private void ensureRegionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          region_ = new java.util.ArrayList<net.combatserver.protobuf.DataStructures.Region>(region_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Region, net.combatserver.protobuf.DataStructures.Region.Builder, net.combatserver.protobuf.DataStructures.RegionOrBuilder> regionBuilder_;
      
      public java.util.List<net.combatserver.protobuf.DataStructures.Region> getRegionList() {
        if (regionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(region_);
        } else {
          return regionBuilder_.getMessageList();
        }
      }
      public int getRegionCount() {
        if (regionBuilder_ == null) {
          return region_.size();
        } else {
          return regionBuilder_.getCount();
        }
      }
      public net.combatserver.protobuf.DataStructures.Region getRegion(int index) {
        if (regionBuilder_ == null) {
          return region_.get(index);
        } else {
          return regionBuilder_.getMessage(index);
        }
      }
      public Builder setRegion(
          int index, net.combatserver.protobuf.DataStructures.Region value) {
        if (regionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegionIsMutable();
          region_.set(index, value);
          onChanged();
        } else {
          regionBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRegion(
          int index, net.combatserver.protobuf.DataStructures.Region.Builder builderForValue) {
        if (regionBuilder_ == null) {
          ensureRegionIsMutable();
          region_.set(index, builderForValue.build());
          onChanged();
        } else {
          regionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRegion(net.combatserver.protobuf.DataStructures.Region value) {
        if (regionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegionIsMutable();
          region_.add(value);
          onChanged();
        } else {
          regionBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRegion(
          int index, net.combatserver.protobuf.DataStructures.Region value) {
        if (regionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegionIsMutable();
          region_.add(index, value);
          onChanged();
        } else {
          regionBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRegion(
          net.combatserver.protobuf.DataStructures.Region.Builder builderForValue) {
        if (regionBuilder_ == null) {
          ensureRegionIsMutable();
          region_.add(builderForValue.build());
          onChanged();
        } else {
          regionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRegion(
          int index, net.combatserver.protobuf.DataStructures.Region.Builder builderForValue) {
        if (regionBuilder_ == null) {
          ensureRegionIsMutable();
          region_.add(index, builderForValue.build());
          onChanged();
        } else {
          regionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRegion(
          java.lang.Iterable<? extends net.combatserver.protobuf.DataStructures.Region> values) {
        if (regionBuilder_ == null) {
          ensureRegionIsMutable();
          super.addAll(values, region_);
          onChanged();
        } else {
          regionBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRegion() {
        if (regionBuilder_ == null) {
          region_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          regionBuilder_.clear();
        }
        return this;
      }
      public Builder removeRegion(int index) {
        if (regionBuilder_ == null) {
          ensureRegionIsMutable();
          region_.remove(index);
          onChanged();
        } else {
          regionBuilder_.remove(index);
        }
        return this;
      }
      public net.combatserver.protobuf.DataStructures.Region.Builder getRegionBuilder(
          int index) {
        return getRegionFieldBuilder().getBuilder(index);
      }
      public net.combatserver.protobuf.DataStructures.RegionOrBuilder getRegionOrBuilder(
          int index) {
        if (regionBuilder_ == null) {
          return region_.get(index);  } else {
          return regionBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.combatserver.protobuf.DataStructures.RegionOrBuilder> 
           getRegionOrBuilderList() {
        if (regionBuilder_ != null) {
          return regionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(region_);
        }
      }
      public net.combatserver.protobuf.DataStructures.Region.Builder addRegionBuilder() {
        return getRegionFieldBuilder().addBuilder(
            net.combatserver.protobuf.DataStructures.Region.getDefaultInstance());
      }
      public net.combatserver.protobuf.DataStructures.Region.Builder addRegionBuilder(
          int index) {
        return getRegionFieldBuilder().addBuilder(
            index, net.combatserver.protobuf.DataStructures.Region.getDefaultInstance());
      }
      public java.util.List<net.combatserver.protobuf.DataStructures.Region.Builder> 
           getRegionBuilderList() {
        return getRegionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Region, net.combatserver.protobuf.DataStructures.Region.Builder, net.combatserver.protobuf.DataStructures.RegionOrBuilder> 
          getRegionFieldBuilder() {
        if (regionBuilder_ == null) {
          regionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.combatserver.protobuf.DataStructures.Region, net.combatserver.protobuf.DataStructures.Region.Builder, net.combatserver.protobuf.DataStructures.RegionOrBuilder>(
                  region_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          region_ = null;
        }
        return regionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.combatserver.protobuf.RegionListNoticeData)
    }
    
    static {
      defaultInstance = new RegionListNoticeData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.combatserver.protobuf.RegionListNoticeData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_combatserver_protobuf_RegionListNoticeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_combatserver_protobuf_RegionListNoticeData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RegionList.proto\022\031net.combatserver.pro" +
      "tobuf\032\024DataStructures.proto\"I\n\024RegionLis" +
      "tNoticeData\0221\n\006region\030\001 \003(\0132!.net.combat" +
      "server.protobuf.RegionB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_combatserver_protobuf_RegionListNoticeData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_combatserver_protobuf_RegionListNoticeData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_combatserver_protobuf_RegionListNoticeData_descriptor,
              new java.lang.String[] { "Region", },
              net.combatserver.protobuf.RegionList.RegionListNoticeData.class,
              net.combatserver.protobuf.RegionList.RegionListNoticeData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.combatserver.protobuf.DataStructures.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
