// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomList.proto

package net.combatserver.protobuf;

public final class RoomList {
  private RoomList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RoomListNoticeDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .net.combatserver.protobuf.Room room = 1;
    java.util.List<net.combatserver.protobuf.DataStructures.Room> 
        getRoomList();
    net.combatserver.protobuf.DataStructures.Room getRoom(int index);
    int getRoomCount();
    java.util.List<? extends net.combatserver.protobuf.DataStructures.RoomOrBuilder> 
        getRoomOrBuilderList();
    net.combatserver.protobuf.DataStructures.RoomOrBuilder getRoomOrBuilder(
        int index);
  }
  public static final class RoomListNoticeData extends
      com.google.protobuf.GeneratedMessage
      implements RoomListNoticeDataOrBuilder {
    // Use RoomListNoticeData.newBuilder() to construct.
    private RoomListNoticeData(Builder builder) {
      super(builder);
    }
    private RoomListNoticeData(boolean noInit) {}
    
    private static final RoomListNoticeData defaultInstance;
    public static RoomListNoticeData getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoomListNoticeData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.combatserver.protobuf.RoomList.internal_static_net_combatserver_protobuf_RoomListNoticeData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.combatserver.protobuf.RoomList.internal_static_net_combatserver_protobuf_RoomListNoticeData_fieldAccessorTable;
    }
    
    // repeated .net.combatserver.protobuf.Room room = 1;
    public static final int ROOM_FIELD_NUMBER = 1;
    private java.util.List<net.combatserver.protobuf.DataStructures.Room> room_;
    public java.util.List<net.combatserver.protobuf.DataStructures.Room> getRoomList() {
      return room_;
    }
    public java.util.List<? extends net.combatserver.protobuf.DataStructures.RoomOrBuilder> 
        getRoomOrBuilderList() {
      return room_;
    }
    public int getRoomCount() {
      return room_.size();
    }
    public net.combatserver.protobuf.DataStructures.Room getRoom(int index) {
      return room_.get(index);
    }
    public net.combatserver.protobuf.DataStructures.RoomOrBuilder getRoomOrBuilder(
        int index) {
      return room_.get(index);
    }
    
    private void initFields() {
      room_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getRoomCount(); i++) {
        if (!getRoom(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < room_.size(); i++) {
        output.writeMessage(1, room_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < room_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, room_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.RoomList.RoomListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.combatserver.protobuf.RoomList.RoomListNoticeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.combatserver.protobuf.RoomList.RoomListNoticeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.combatserver.protobuf.RoomList.internal_static_net_combatserver_protobuf_RoomListNoticeData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.combatserver.protobuf.RoomList.internal_static_net_combatserver_protobuf_RoomListNoticeData_fieldAccessorTable;
      }
      
      // Construct using net.combatserver.protobuf.RoomList.RoomListNoticeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoomFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (roomBuilder_ == null) {
          room_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          roomBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.combatserver.protobuf.RoomList.RoomListNoticeData.getDescriptor();
      }
      
      public net.combatserver.protobuf.RoomList.RoomListNoticeData getDefaultInstanceForType() {
        return net.combatserver.protobuf.RoomList.RoomListNoticeData.getDefaultInstance();
      }
      
      public net.combatserver.protobuf.RoomList.RoomListNoticeData build() {
        net.combatserver.protobuf.RoomList.RoomListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.combatserver.protobuf.RoomList.RoomListNoticeData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.combatserver.protobuf.RoomList.RoomListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.combatserver.protobuf.RoomList.RoomListNoticeData buildPartial() {
        net.combatserver.protobuf.RoomList.RoomListNoticeData result = new net.combatserver.protobuf.RoomList.RoomListNoticeData(this);
        int from_bitField0_ = bitField0_;
        if (roomBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            room_ = java.util.Collections.unmodifiableList(room_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.room_ = room_;
        } else {
          result.room_ = roomBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.combatserver.protobuf.RoomList.RoomListNoticeData) {
          return mergeFrom((net.combatserver.protobuf.RoomList.RoomListNoticeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.combatserver.protobuf.RoomList.RoomListNoticeData other) {
        if (other == net.combatserver.protobuf.RoomList.RoomListNoticeData.getDefaultInstance()) return this;
        if (roomBuilder_ == null) {
          if (!other.room_.isEmpty()) {
            if (room_.isEmpty()) {
              room_ = other.room_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRoomIsMutable();
              room_.addAll(other.room_);
            }
            onChanged();
          }
        } else {
          if (!other.room_.isEmpty()) {
            if (roomBuilder_.isEmpty()) {
              roomBuilder_.dispose();
              roomBuilder_ = null;
              room_ = other.room_;
              bitField0_ = (bitField0_ & ~0x00000001);
              roomBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoomFieldBuilder() : null;
            } else {
              roomBuilder_.addAllMessages(other.room_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getRoomCount(); i++) {
          if (!getRoom(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              net.combatserver.protobuf.DataStructures.Room.Builder subBuilder = net.combatserver.protobuf.DataStructures.Room.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRoom(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .net.combatserver.protobuf.Room room = 1;
      private java.util.List<net.combatserver.protobuf.DataStructures.Room> room_ =
        java.util.Collections.emptyList();
      private void ensureRoomIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          room_ = new java.util.ArrayList<net.combatserver.protobuf.DataStructures.Room>(room_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Room, net.combatserver.protobuf.DataStructures.Room.Builder, net.combatserver.protobuf.DataStructures.RoomOrBuilder> roomBuilder_;
      
      public java.util.List<net.combatserver.protobuf.DataStructures.Room> getRoomList() {
        if (roomBuilder_ == null) {
          return java.util.Collections.unmodifiableList(room_);
        } else {
          return roomBuilder_.getMessageList();
        }
      }
      public int getRoomCount() {
        if (roomBuilder_ == null) {
          return room_.size();
        } else {
          return roomBuilder_.getCount();
        }
      }
      public net.combatserver.protobuf.DataStructures.Room getRoom(int index) {
        if (roomBuilder_ == null) {
          return room_.get(index);
        } else {
          return roomBuilder_.getMessage(index);
        }
      }
      public Builder setRoom(
          int index, net.combatserver.protobuf.DataStructures.Room value) {
        if (roomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomIsMutable();
          room_.set(index, value);
          onChanged();
        } else {
          roomBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRoom(
          int index, net.combatserver.protobuf.DataStructures.Room.Builder builderForValue) {
        if (roomBuilder_ == null) {
          ensureRoomIsMutable();
          room_.set(index, builderForValue.build());
          onChanged();
        } else {
          roomBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRoom(net.combatserver.protobuf.DataStructures.Room value) {
        if (roomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomIsMutable();
          room_.add(value);
          onChanged();
        } else {
          roomBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRoom(
          int index, net.combatserver.protobuf.DataStructures.Room value) {
        if (roomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomIsMutable();
          room_.add(index, value);
          onChanged();
        } else {
          roomBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRoom(
          net.combatserver.protobuf.DataStructures.Room.Builder builderForValue) {
        if (roomBuilder_ == null) {
          ensureRoomIsMutable();
          room_.add(builderForValue.build());
          onChanged();
        } else {
          roomBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRoom(
          int index, net.combatserver.protobuf.DataStructures.Room.Builder builderForValue) {
        if (roomBuilder_ == null) {
          ensureRoomIsMutable();
          room_.add(index, builderForValue.build());
          onChanged();
        } else {
          roomBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRoom(
          java.lang.Iterable<? extends net.combatserver.protobuf.DataStructures.Room> values) {
        if (roomBuilder_ == null) {
          ensureRoomIsMutable();
          super.addAll(values, room_);
          onChanged();
        } else {
          roomBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRoom() {
        if (roomBuilder_ == null) {
          room_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          roomBuilder_.clear();
        }
        return this;
      }
      public Builder removeRoom(int index) {
        if (roomBuilder_ == null) {
          ensureRoomIsMutable();
          room_.remove(index);
          onChanged();
        } else {
          roomBuilder_.remove(index);
        }
        return this;
      }
      public net.combatserver.protobuf.DataStructures.Room.Builder getRoomBuilder(
          int index) {
        return getRoomFieldBuilder().getBuilder(index);
      }
      public net.combatserver.protobuf.DataStructures.RoomOrBuilder getRoomOrBuilder(
          int index) {
        if (roomBuilder_ == null) {
          return room_.get(index);  } else {
          return roomBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.combatserver.protobuf.DataStructures.RoomOrBuilder> 
           getRoomOrBuilderList() {
        if (roomBuilder_ != null) {
          return roomBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(room_);
        }
      }
      public net.combatserver.protobuf.DataStructures.Room.Builder addRoomBuilder() {
        return getRoomFieldBuilder().addBuilder(
            net.combatserver.protobuf.DataStructures.Room.getDefaultInstance());
      }
      public net.combatserver.protobuf.DataStructures.Room.Builder addRoomBuilder(
          int index) {
        return getRoomFieldBuilder().addBuilder(
            index, net.combatserver.protobuf.DataStructures.Room.getDefaultInstance());
      }
      public java.util.List<net.combatserver.protobuf.DataStructures.Room.Builder> 
           getRoomBuilderList() {
        return getRoomFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Room, net.combatserver.protobuf.DataStructures.Room.Builder, net.combatserver.protobuf.DataStructures.RoomOrBuilder> 
          getRoomFieldBuilder() {
        if (roomBuilder_ == null) {
          roomBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.combatserver.protobuf.DataStructures.Room, net.combatserver.protobuf.DataStructures.Room.Builder, net.combatserver.protobuf.DataStructures.RoomOrBuilder>(
                  room_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          room_ = null;
        }
        return roomBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.combatserver.protobuf.RoomListNoticeData)
    }
    
    static {
      defaultInstance = new RoomListNoticeData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.combatserver.protobuf.RoomListNoticeData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_combatserver_protobuf_RoomListNoticeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_combatserver_protobuf_RoomListNoticeData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016RoomList.proto\022\031net.combatserver.proto" +
      "buf\032\024DataStructures.proto\"C\n\022RoomListNot" +
      "iceData\022-\n\004room\030\001 \003(\0132\037.net.combatserver" +
      ".protobuf.RoomB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_combatserver_protobuf_RoomListNoticeData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_combatserver_protobuf_RoomListNoticeData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_combatserver_protobuf_RoomListNoticeData_descriptor,
              new java.lang.String[] { "Room", },
              net.combatserver.protobuf.RoomList.RoomListNoticeData.class,
              net.combatserver.protobuf.RoomList.RoomListNoticeData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.combatserver.protobuf.DataStructures.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
