// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserList.proto

package net.combatserver.protobuf;

public final class UserList {
  private UserList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserListNoticeDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .net.combatserver.protobuf.User user = 1;
    java.util.List<net.combatserver.protobuf.DataStructures.User> 
        getUserList();
    net.combatserver.protobuf.DataStructures.User getUser(int index);
    int getUserCount();
    java.util.List<? extends net.combatserver.protobuf.DataStructures.UserOrBuilder> 
        getUserOrBuilderList();
    net.combatserver.protobuf.DataStructures.UserOrBuilder getUserOrBuilder(
        int index);
  }
  public static final class UserListNoticeData extends
      com.google.protobuf.GeneratedMessage
      implements UserListNoticeDataOrBuilder {
    // Use UserListNoticeData.newBuilder() to construct.
    private UserListNoticeData(Builder builder) {
      super(builder);
    }
    private UserListNoticeData(boolean noInit) {}
    
    private static final UserListNoticeData defaultInstance;
    public static UserListNoticeData getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserListNoticeData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.combatserver.protobuf.UserList.internal_static_net_combatserver_protobuf_UserListNoticeData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.combatserver.protobuf.UserList.internal_static_net_combatserver_protobuf_UserListNoticeData_fieldAccessorTable;
    }
    
    // repeated .net.combatserver.protobuf.User user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.util.List<net.combatserver.protobuf.DataStructures.User> user_;
    public java.util.List<net.combatserver.protobuf.DataStructures.User> getUserList() {
      return user_;
    }
    public java.util.List<? extends net.combatserver.protobuf.DataStructures.UserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    public int getUserCount() {
      return user_.size();
    }
    public net.combatserver.protobuf.DataStructures.User getUser(int index) {
      return user_.get(index);
    }
    public net.combatserver.protobuf.DataStructures.UserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }
    
    private void initFields() {
      user_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getUserCount(); i++) {
        if (!getUser(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(1, user_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.UserList.UserListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.combatserver.protobuf.UserList.UserListNoticeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.combatserver.protobuf.UserList.UserListNoticeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.combatserver.protobuf.UserList.internal_static_net_combatserver_protobuf_UserListNoticeData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.combatserver.protobuf.UserList.internal_static_net_combatserver_protobuf_UserListNoticeData_fieldAccessorTable;
      }
      
      // Construct using net.combatserver.protobuf.UserList.UserListNoticeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.combatserver.protobuf.UserList.UserListNoticeData.getDescriptor();
      }
      
      public net.combatserver.protobuf.UserList.UserListNoticeData getDefaultInstanceForType() {
        return net.combatserver.protobuf.UserList.UserListNoticeData.getDefaultInstance();
      }
      
      public net.combatserver.protobuf.UserList.UserListNoticeData build() {
        net.combatserver.protobuf.UserList.UserListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.combatserver.protobuf.UserList.UserListNoticeData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.combatserver.protobuf.UserList.UserListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.combatserver.protobuf.UserList.UserListNoticeData buildPartial() {
        net.combatserver.protobuf.UserList.UserListNoticeData result = new net.combatserver.protobuf.UserList.UserListNoticeData(this);
        int from_bitField0_ = bitField0_;
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.combatserver.protobuf.UserList.UserListNoticeData) {
          return mergeFrom((net.combatserver.protobuf.UserList.UserListNoticeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.combatserver.protobuf.UserList.UserListNoticeData other) {
        if (other == net.combatserver.protobuf.UserList.UserListNoticeData.getDefaultInstance()) return this;
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getUserCount(); i++) {
          if (!getUser(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              net.combatserver.protobuf.DataStructures.User.Builder subBuilder = net.combatserver.protobuf.DataStructures.User.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUser(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .net.combatserver.protobuf.User user = 1;
      private java.util.List<net.combatserver.protobuf.DataStructures.User> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          user_ = new java.util.ArrayList<net.combatserver.protobuf.DataStructures.User>(user_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.User, net.combatserver.protobuf.DataStructures.User.Builder, net.combatserver.protobuf.DataStructures.UserOrBuilder> userBuilder_;
      
      public java.util.List<net.combatserver.protobuf.DataStructures.User> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      public net.combatserver.protobuf.DataStructures.User getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      public Builder setUser(
          int index, net.combatserver.protobuf.DataStructures.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUser(
          int index, net.combatserver.protobuf.DataStructures.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUser(net.combatserver.protobuf.DataStructures.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUser(
          int index, net.combatserver.protobuf.DataStructures.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUser(
          net.combatserver.protobuf.DataStructures.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUser(
          int index, net.combatserver.protobuf.DataStructures.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUser(
          java.lang.Iterable<? extends net.combatserver.protobuf.DataStructures.User> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          super.addAll(values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      public net.combatserver.protobuf.DataStructures.User.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      public net.combatserver.protobuf.DataStructures.UserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.combatserver.protobuf.DataStructures.UserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      public net.combatserver.protobuf.DataStructures.User.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            net.combatserver.protobuf.DataStructures.User.getDefaultInstance());
      }
      public net.combatserver.protobuf.DataStructures.User.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, net.combatserver.protobuf.DataStructures.User.getDefaultInstance());
      }
      public java.util.List<net.combatserver.protobuf.DataStructures.User.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.User, net.combatserver.protobuf.DataStructures.User.Builder, net.combatserver.protobuf.DataStructures.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.combatserver.protobuf.DataStructures.User, net.combatserver.protobuf.DataStructures.User.Builder, net.combatserver.protobuf.DataStructures.UserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.combatserver.protobuf.UserListNoticeData)
    }
    
    static {
      defaultInstance = new UserListNoticeData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.combatserver.protobuf.UserListNoticeData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_combatserver_protobuf_UserListNoticeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_combatserver_protobuf_UserListNoticeData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016UserList.proto\022\031net.combatserver.proto" +
      "buf\032\024DataStructures.proto\"C\n\022UserListNot" +
      "iceData\022-\n\004user\030\001 \003(\0132\037.net.combatserver" +
      ".protobuf.UserB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_combatserver_protobuf_UserListNoticeData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_combatserver_protobuf_UserListNoticeData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_combatserver_protobuf_UserListNoticeData_descriptor,
              new java.lang.String[] { "User", },
              net.combatserver.protobuf.UserList.UserListNoticeData.class,
              net.combatserver.protobuf.UserList.UserListNoticeData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.combatserver.protobuf.DataStructures.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
