// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserPropertyUpdate.proto

package net.combatserver.protobuf;

public final class UserPropertyUpdate {
  private UserPropertyUpdate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserPropertyUpdateRequestDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .net.combatserver.protobuf.Property property = 1;
    boolean hasProperty();
    net.combatserver.protobuf.DataStructures.Property getProperty();
    net.combatserver.protobuf.DataStructures.PropertyOrBuilder getPropertyOrBuilder();
  }
  public static final class UserPropertyUpdateRequestData extends
      com.google.protobuf.GeneratedMessage
      implements UserPropertyUpdateRequestDataOrBuilder {
    // Use UserPropertyUpdateRequestData.newBuilder() to construct.
    private UserPropertyUpdateRequestData(Builder builder) {
      super(builder);
    }
    private UserPropertyUpdateRequestData(boolean noInit) {}
    
    private static final UserPropertyUpdateRequestData defaultInstance;
    public static UserPropertyUpdateRequestData getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserPropertyUpdateRequestData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .net.combatserver.protobuf.Property property = 1;
    public static final int PROPERTY_FIELD_NUMBER = 1;
    private net.combatserver.protobuf.DataStructures.Property property_;
    public boolean hasProperty() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public net.combatserver.protobuf.DataStructures.Property getProperty() {
      return property_;
    }
    public net.combatserver.protobuf.DataStructures.PropertyOrBuilder getPropertyOrBuilder() {
      return property_;
    }
    
    private void initFields() {
      property_ = net.combatserver.protobuf.DataStructures.Property.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasProperty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getProperty().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, property_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, property_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_fieldAccessorTable;
      }
      
      // Construct using net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (propertyBuilder_ == null) {
          property_ = net.combatserver.protobuf.DataStructures.Property.getDefaultInstance();
        } else {
          propertyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData.getDescriptor();
      }
      
      public net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData getDefaultInstanceForType() {
        return net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData.getDefaultInstance();
      }
      
      public net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData build() {
        net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData buildPartial() {
        net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData result = new net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (propertyBuilder_ == null) {
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData) {
          return mergeFrom((net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData other) {
        if (other == net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData.getDefaultInstance()) return this;
        if (other.hasProperty()) {
          mergeProperty(other.getProperty());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasProperty()) {
          
          return false;
        }
        if (!getProperty().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              net.combatserver.protobuf.DataStructures.Property.Builder subBuilder = net.combatserver.protobuf.DataStructures.Property.newBuilder();
              if (hasProperty()) {
                subBuilder.mergeFrom(getProperty());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProperty(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .net.combatserver.protobuf.Property property = 1;
      private net.combatserver.protobuf.DataStructures.Property property_ = net.combatserver.protobuf.DataStructures.Property.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          net.combatserver.protobuf.DataStructures.Property, net.combatserver.protobuf.DataStructures.Property.Builder, net.combatserver.protobuf.DataStructures.PropertyOrBuilder> propertyBuilder_;
      public boolean hasProperty() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public net.combatserver.protobuf.DataStructures.Property getProperty() {
        if (propertyBuilder_ == null) {
          return property_;
        } else {
          return propertyBuilder_.getMessage();
        }
      }
      public Builder setProperty(net.combatserver.protobuf.DataStructures.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          property_ = value;
          onChanged();
        } else {
          propertyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setProperty(
          net.combatserver.protobuf.DataStructures.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          property_ = builderForValue.build();
          onChanged();
        } else {
          propertyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeProperty(net.combatserver.protobuf.DataStructures.Property value) {
        if (propertyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              property_ != net.combatserver.protobuf.DataStructures.Property.getDefaultInstance()) {
            property_ =
              net.combatserver.protobuf.DataStructures.Property.newBuilder(property_).mergeFrom(value).buildPartial();
          } else {
            property_ = value;
          }
          onChanged();
        } else {
          propertyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = net.combatserver.protobuf.DataStructures.Property.getDefaultInstance();
          onChanged();
        } else {
          propertyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public net.combatserver.protobuf.DataStructures.Property.Builder getPropertyBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPropertyFieldBuilder().getBuilder();
      }
      public net.combatserver.protobuf.DataStructures.PropertyOrBuilder getPropertyOrBuilder() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilder();
        } else {
          return property_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          net.combatserver.protobuf.DataStructures.Property, net.combatserver.protobuf.DataStructures.Property.Builder, net.combatserver.protobuf.DataStructures.PropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.combatserver.protobuf.DataStructures.Property, net.combatserver.protobuf.DataStructures.Property.Builder, net.combatserver.protobuf.DataStructures.PropertyOrBuilder>(
                  property_,
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.combatserver.protobuf.UserPropertyUpdateRequestData)
    }
    
    static {
      defaultInstance = new UserPropertyUpdateRequestData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.combatserver.protobuf.UserPropertyUpdateRequestData)
  }
  
  public interface UserPropertyUpdateNoticeDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // repeated .net.combatserver.protobuf.Property properties = 2;
    java.util.List<net.combatserver.protobuf.DataStructures.Property> 
        getPropertiesList();
    net.combatserver.protobuf.DataStructures.Property getProperties(int index);
    int getPropertiesCount();
    java.util.List<? extends net.combatserver.protobuf.DataStructures.PropertyOrBuilder> 
        getPropertiesOrBuilderList();
    net.combatserver.protobuf.DataStructures.PropertyOrBuilder getPropertiesOrBuilder(
        int index);
  }
  public static final class UserPropertyUpdateNoticeData extends
      com.google.protobuf.GeneratedMessage
      implements UserPropertyUpdateNoticeDataOrBuilder {
    // Use UserPropertyUpdateNoticeData.newBuilder() to construct.
    private UserPropertyUpdateNoticeData(Builder builder) {
      super(builder);
    }
    private UserPropertyUpdateNoticeData(boolean noInit) {}
    
    private static final UserPropertyUpdateNoticeData defaultInstance;
    public static UserPropertyUpdateNoticeData getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserPropertyUpdateNoticeData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // repeated .net.combatserver.protobuf.Property properties = 2;
    public static final int PROPERTIES_FIELD_NUMBER = 2;
    private java.util.List<net.combatserver.protobuf.DataStructures.Property> properties_;
    public java.util.List<net.combatserver.protobuf.DataStructures.Property> getPropertiesList() {
      return properties_;
    }
    public java.util.List<? extends net.combatserver.protobuf.DataStructures.PropertyOrBuilder> 
        getPropertiesOrBuilderList() {
      return properties_;
    }
    public int getPropertiesCount() {
      return properties_.size();
    }
    public net.combatserver.protobuf.DataStructures.Property getProperties(int index) {
      return properties_.get(index);
    }
    public net.combatserver.protobuf.DataStructures.PropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }
    
    private void initFields() {
      id_ = 0;
      properties_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropertiesCount(); i++) {
        if (!getProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(2, properties_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, properties_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.combatserver.protobuf.UserPropertyUpdate.internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_fieldAccessorTable;
      }
      
      // Construct using net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData.getDescriptor();
      }
      
      public net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData getDefaultInstanceForType() {
        return net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData.getDefaultInstance();
      }
      
      public net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData build() {
        net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData buildPartial() {
        net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData result = new net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData) {
          return mergeFrom((net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData other) {
        if (other == net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000002);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getPropertiesCount(); i++) {
          if (!getProperties(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              net.combatserver.protobuf.DataStructures.Property.Builder subBuilder = net.combatserver.protobuf.DataStructures.Property.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperties(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .net.combatserver.protobuf.Property properties = 2;
      private java.util.List<net.combatserver.protobuf.DataStructures.Property> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          properties_ = new java.util.ArrayList<net.combatserver.protobuf.DataStructures.Property>(properties_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Property, net.combatserver.protobuf.DataStructures.Property.Builder, net.combatserver.protobuf.DataStructures.PropertyOrBuilder> propertiesBuilder_;
      
      public java.util.List<net.combatserver.protobuf.DataStructures.Property> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      public net.combatserver.protobuf.DataStructures.Property getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      public Builder setProperties(
          int index, net.combatserver.protobuf.DataStructures.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProperties(
          int index, net.combatserver.protobuf.DataStructures.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProperties(net.combatserver.protobuf.DataStructures.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProperties(
          int index, net.combatserver.protobuf.DataStructures.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProperties(
          net.combatserver.protobuf.DataStructures.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProperties(
          int index, net.combatserver.protobuf.DataStructures.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProperties(
          java.lang.Iterable<? extends net.combatserver.protobuf.DataStructures.Property> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          super.addAll(values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      public net.combatserver.protobuf.DataStructures.Property.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      public net.combatserver.protobuf.DataStructures.PropertyOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.combatserver.protobuf.DataStructures.PropertyOrBuilder> 
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      public net.combatserver.protobuf.DataStructures.Property.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            net.combatserver.protobuf.DataStructures.Property.getDefaultInstance());
      }
      public net.combatserver.protobuf.DataStructures.Property.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, net.combatserver.protobuf.DataStructures.Property.getDefaultInstance());
      }
      public java.util.List<net.combatserver.protobuf.DataStructures.Property.Builder> 
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Property, net.combatserver.protobuf.DataStructures.Property.Builder, net.combatserver.protobuf.DataStructures.PropertyOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.combatserver.protobuf.DataStructures.Property, net.combatserver.protobuf.DataStructures.Property.Builder, net.combatserver.protobuf.DataStructures.PropertyOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.combatserver.protobuf.UserPropertyUpdateNoticeData)
    }
    
    static {
      defaultInstance = new UserPropertyUpdateNoticeData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.combatserver.protobuf.UserPropertyUpdateNoticeData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030UserPropertyUpdate.proto\022\031net.combatse" +
      "rver.protobuf\032\024DataStructures.proto\"V\n\035U" +
      "serPropertyUpdateRequestData\0225\n\010property" +
      "\030\001 \002(\0132#.net.combatserver.protobuf.Prope" +
      "rty\"c\n\034UserPropertyUpdateNoticeData\022\n\n\002i" +
      "d\030\001 \002(\005\0227\n\nproperties\030\002 \003(\0132#.net.combat" +
      "server.protobuf.PropertyB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_combatserver_protobuf_UserPropertyUpdateRequestData_descriptor,
              new java.lang.String[] { "Property", },
              net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData.class,
              net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateRequestData.Builder.class);
          internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_combatserver_protobuf_UserPropertyUpdateNoticeData_descriptor,
              new java.lang.String[] { "Id", "Properties", },
              net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData.class,
              net.combatserver.protobuf.UserPropertyUpdate.UserPropertyUpdateNoticeData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.combatserver.protobuf.DataStructures.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
