// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZoneList.proto

package net.combatserver.protobuf;

public final class ZoneList {
  private ZoneList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ZoneListNoticeDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .net.combatserver.protobuf.Zone zone = 1;
    java.util.List<net.combatserver.protobuf.DataStructures.Zone> 
        getZoneList();
    net.combatserver.protobuf.DataStructures.Zone getZone(int index);
    int getZoneCount();
    java.util.List<? extends net.combatserver.protobuf.DataStructures.ZoneOrBuilder> 
        getZoneOrBuilderList();
    net.combatserver.protobuf.DataStructures.ZoneOrBuilder getZoneOrBuilder(
        int index);
  }
  public static final class ZoneListNoticeData extends
      com.google.protobuf.GeneratedMessage
      implements ZoneListNoticeDataOrBuilder {
    // Use ZoneListNoticeData.newBuilder() to construct.
    private ZoneListNoticeData(Builder builder) {
      super(builder);
    }
    private ZoneListNoticeData(boolean noInit) {}
    
    private static final ZoneListNoticeData defaultInstance;
    public static ZoneListNoticeData getDefaultInstance() {
      return defaultInstance;
    }
    
    public ZoneListNoticeData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.combatserver.protobuf.ZoneList.internal_static_net_combatserver_protobuf_ZoneListNoticeData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.combatserver.protobuf.ZoneList.internal_static_net_combatserver_protobuf_ZoneListNoticeData_fieldAccessorTable;
    }
    
    // repeated .net.combatserver.protobuf.Zone zone = 1;
    public static final int ZONE_FIELD_NUMBER = 1;
    private java.util.List<net.combatserver.protobuf.DataStructures.Zone> zone_;
    public java.util.List<net.combatserver.protobuf.DataStructures.Zone> getZoneList() {
      return zone_;
    }
    public java.util.List<? extends net.combatserver.protobuf.DataStructures.ZoneOrBuilder> 
        getZoneOrBuilderList() {
      return zone_;
    }
    public int getZoneCount() {
      return zone_.size();
    }
    public net.combatserver.protobuf.DataStructures.Zone getZone(int index) {
      return zone_.get(index);
    }
    public net.combatserver.protobuf.DataStructures.ZoneOrBuilder getZoneOrBuilder(
        int index) {
      return zone_.get(index);
    }
    
    private void initFields() {
      zone_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getZoneCount(); i++) {
        if (!getZone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < zone_.size(); i++) {
        output.writeMessage(1, zone_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < zone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, zone_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.combatserver.protobuf.ZoneList.ZoneListNoticeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.combatserver.protobuf.ZoneList.ZoneListNoticeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.combatserver.protobuf.ZoneList.ZoneListNoticeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.combatserver.protobuf.ZoneList.internal_static_net_combatserver_protobuf_ZoneListNoticeData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.combatserver.protobuf.ZoneList.internal_static_net_combatserver_protobuf_ZoneListNoticeData_fieldAccessorTable;
      }
      
      // Construct using net.combatserver.protobuf.ZoneList.ZoneListNoticeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getZoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (zoneBuilder_ == null) {
          zone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          zoneBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.combatserver.protobuf.ZoneList.ZoneListNoticeData.getDescriptor();
      }
      
      public net.combatserver.protobuf.ZoneList.ZoneListNoticeData getDefaultInstanceForType() {
        return net.combatserver.protobuf.ZoneList.ZoneListNoticeData.getDefaultInstance();
      }
      
      public net.combatserver.protobuf.ZoneList.ZoneListNoticeData build() {
        net.combatserver.protobuf.ZoneList.ZoneListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.combatserver.protobuf.ZoneList.ZoneListNoticeData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.combatserver.protobuf.ZoneList.ZoneListNoticeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.combatserver.protobuf.ZoneList.ZoneListNoticeData buildPartial() {
        net.combatserver.protobuf.ZoneList.ZoneListNoticeData result = new net.combatserver.protobuf.ZoneList.ZoneListNoticeData(this);
        int from_bitField0_ = bitField0_;
        if (zoneBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            zone_ = java.util.Collections.unmodifiableList(zone_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.zone_ = zone_;
        } else {
          result.zone_ = zoneBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.combatserver.protobuf.ZoneList.ZoneListNoticeData) {
          return mergeFrom((net.combatserver.protobuf.ZoneList.ZoneListNoticeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.combatserver.protobuf.ZoneList.ZoneListNoticeData other) {
        if (other == net.combatserver.protobuf.ZoneList.ZoneListNoticeData.getDefaultInstance()) return this;
        if (zoneBuilder_ == null) {
          if (!other.zone_.isEmpty()) {
            if (zone_.isEmpty()) {
              zone_ = other.zone_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureZoneIsMutable();
              zone_.addAll(other.zone_);
            }
            onChanged();
          }
        } else {
          if (!other.zone_.isEmpty()) {
            if (zoneBuilder_.isEmpty()) {
              zoneBuilder_.dispose();
              zoneBuilder_ = null;
              zone_ = other.zone_;
              bitField0_ = (bitField0_ & ~0x00000001);
              zoneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getZoneFieldBuilder() : null;
            } else {
              zoneBuilder_.addAllMessages(other.zone_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getZoneCount(); i++) {
          if (!getZone(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              net.combatserver.protobuf.DataStructures.Zone.Builder subBuilder = net.combatserver.protobuf.DataStructures.Zone.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addZone(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .net.combatserver.protobuf.Zone zone = 1;
      private java.util.List<net.combatserver.protobuf.DataStructures.Zone> zone_ =
        java.util.Collections.emptyList();
      private void ensureZoneIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          zone_ = new java.util.ArrayList<net.combatserver.protobuf.DataStructures.Zone>(zone_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Zone, net.combatserver.protobuf.DataStructures.Zone.Builder, net.combatserver.protobuf.DataStructures.ZoneOrBuilder> zoneBuilder_;
      
      public java.util.List<net.combatserver.protobuf.DataStructures.Zone> getZoneList() {
        if (zoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(zone_);
        } else {
          return zoneBuilder_.getMessageList();
        }
      }
      public int getZoneCount() {
        if (zoneBuilder_ == null) {
          return zone_.size();
        } else {
          return zoneBuilder_.getCount();
        }
      }
      public net.combatserver.protobuf.DataStructures.Zone getZone(int index) {
        if (zoneBuilder_ == null) {
          return zone_.get(index);
        } else {
          return zoneBuilder_.getMessage(index);
        }
      }
      public Builder setZone(
          int index, net.combatserver.protobuf.DataStructures.Zone value) {
        if (zoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureZoneIsMutable();
          zone_.set(index, value);
          onChanged();
        } else {
          zoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setZone(
          int index, net.combatserver.protobuf.DataStructures.Zone.Builder builderForValue) {
        if (zoneBuilder_ == null) {
          ensureZoneIsMutable();
          zone_.set(index, builderForValue.build());
          onChanged();
        } else {
          zoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addZone(net.combatserver.protobuf.DataStructures.Zone value) {
        if (zoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureZoneIsMutable();
          zone_.add(value);
          onChanged();
        } else {
          zoneBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addZone(
          int index, net.combatserver.protobuf.DataStructures.Zone value) {
        if (zoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureZoneIsMutable();
          zone_.add(index, value);
          onChanged();
        } else {
          zoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addZone(
          net.combatserver.protobuf.DataStructures.Zone.Builder builderForValue) {
        if (zoneBuilder_ == null) {
          ensureZoneIsMutable();
          zone_.add(builderForValue.build());
          onChanged();
        } else {
          zoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addZone(
          int index, net.combatserver.protobuf.DataStructures.Zone.Builder builderForValue) {
        if (zoneBuilder_ == null) {
          ensureZoneIsMutable();
          zone_.add(index, builderForValue.build());
          onChanged();
        } else {
          zoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllZone(
          java.lang.Iterable<? extends net.combatserver.protobuf.DataStructures.Zone> values) {
        if (zoneBuilder_ == null) {
          ensureZoneIsMutable();
          super.addAll(values, zone_);
          onChanged();
        } else {
          zoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearZone() {
        if (zoneBuilder_ == null) {
          zone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          zoneBuilder_.clear();
        }
        return this;
      }
      public Builder removeZone(int index) {
        if (zoneBuilder_ == null) {
          ensureZoneIsMutable();
          zone_.remove(index);
          onChanged();
        } else {
          zoneBuilder_.remove(index);
        }
        return this;
      }
      public net.combatserver.protobuf.DataStructures.Zone.Builder getZoneBuilder(
          int index) {
        return getZoneFieldBuilder().getBuilder(index);
      }
      public net.combatserver.protobuf.DataStructures.ZoneOrBuilder getZoneOrBuilder(
          int index) {
        if (zoneBuilder_ == null) {
          return zone_.get(index);  } else {
          return zoneBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.combatserver.protobuf.DataStructures.ZoneOrBuilder> 
           getZoneOrBuilderList() {
        if (zoneBuilder_ != null) {
          return zoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(zone_);
        }
      }
      public net.combatserver.protobuf.DataStructures.Zone.Builder addZoneBuilder() {
        return getZoneFieldBuilder().addBuilder(
            net.combatserver.protobuf.DataStructures.Zone.getDefaultInstance());
      }
      public net.combatserver.protobuf.DataStructures.Zone.Builder addZoneBuilder(
          int index) {
        return getZoneFieldBuilder().addBuilder(
            index, net.combatserver.protobuf.DataStructures.Zone.getDefaultInstance());
      }
      public java.util.List<net.combatserver.protobuf.DataStructures.Zone.Builder> 
           getZoneBuilderList() {
        return getZoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.combatserver.protobuf.DataStructures.Zone, net.combatserver.protobuf.DataStructures.Zone.Builder, net.combatserver.protobuf.DataStructures.ZoneOrBuilder> 
          getZoneFieldBuilder() {
        if (zoneBuilder_ == null) {
          zoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.combatserver.protobuf.DataStructures.Zone, net.combatserver.protobuf.DataStructures.Zone.Builder, net.combatserver.protobuf.DataStructures.ZoneOrBuilder>(
                  zone_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          zone_ = null;
        }
        return zoneBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.combatserver.protobuf.ZoneListNoticeData)
    }
    
    static {
      defaultInstance = new ZoneListNoticeData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.combatserver.protobuf.ZoneListNoticeData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_combatserver_protobuf_ZoneListNoticeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_combatserver_protobuf_ZoneListNoticeData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ZoneList.proto\022\031net.combatserver.proto" +
      "buf\032\024DataStructures.proto\"C\n\022ZoneListNot" +
      "iceData\022-\n\004zone\030\001 \003(\0132\037.net.combatserver" +
      ".protobuf.ZoneB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_combatserver_protobuf_ZoneListNoticeData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_combatserver_protobuf_ZoneListNoticeData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_combatserver_protobuf_ZoneListNoticeData_descriptor,
              new java.lang.String[] { "Zone", },
              net.combatserver.protobuf.ZoneList.ZoneListNoticeData.class,
              net.combatserver.protobuf.ZoneList.ZoneListNoticeData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.combatserver.protobuf.DataStructures.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
